#!/bin/sh
#set the repo location to the hostname
HOST='{hostname}'
REPO=backups@jumpbox.homelab:/mnt/nas/storage/Backups/servers/$HOST.homelab-test

borgpid=$(ps aux | grep -v grep | grep borg | wc -l)
#Bail if borg is already running, maybe previous run didn't finish
if [ $borgpid -gt 0 ]; then
    echo "Backup already running"
    exit
fi

# Backup home directory
borg create -v --stats                          \
    $REPO::$HOST'.homelab-{now:%d-%m-%Y}'                   \
    /home/jack

#Prune expired backups
#7 daily, 4 weekly and 6 monthly backups are what is kept
echo "Pruning expired backups"
borg prune -v --list $REPO --prefix $HOST'.homelab' \
    --keep-daily=7 --keep-weekly=4 --keep-monthly=6
~
