#!/bin/sh
#set the repo location to the hostname
HOST='{hostname}'
DOMAIN=.homelab
REPO=backups@jumpbox.homelab:/mnt/nas/storage/Backups/servers/$HOST$DOMAIN

# Backup home directory
borg init --encryption=none $REPO
echo Repo created
echo Jack is the best 2018
